--- #YAML:1.0
name:                Tk-LogScale
version:             0.09
abstract:            A logarithmic Scale widget
license:             perl
author:              
    - Slaven Rezic (srezic@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Tk:                            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
